print ("Hello  \"world\" World")
print ("pooja  'pooja' taksande")
print('I\'m pooja')
print("line a\nline b")   #(\n is use for new line)
print("POOJA\tGAN\bNVIR")
print("pooja taksande\\\\") #(\\is for backslassh)
print ("pooja \\n ganvir") 
print ("this is double backslash \\\\") #(\\\\treat as 2 \\)
print ("\" \'")
print ("this is \\\\ double backslash")
print ("these are /\\/\\/\\/\\/\\ mountains")
print ("he is\tawesome")
print ("\\\" \\n \\t \\\'")