age=input("enter your age?")
age=int(age)
if age >= 14: #(if block execute when if statement is true)
    print("you are above 14")
    print("you are eligible for game")
else:   #(else block is execute when if statement is false)
    print("you are below 14")
    print("you are not eligible for game")