#syntax [start argument:stop argument:step argument]
lang="python"
print ("pooja" [1:3])
print ("harshit" [1:5:1]) #(it will print full string starting from a to h)
print ("harshit" [0:5:2]) #(it will print character after 2 step)
print (lang[0:6:3])
print("sudhakar" [1:8:3])
print ("harshit" [0::2]) #(stop argumentbis not given)
print ("harshit" [::3])
print ("mangala" [5::-1])  #(start argument from 5 means l...-1 is for reverse step argument)
print ("rajashree" [-1::-1]) #(start argument with -1 means last no of string with reverse 1 step)
print ("rajashree" [::-1])
print ("rajashree" [-1::-2])
print ("rajashree" [-1::2])
print (lang[1:5:2])
print ("rajashreemoon" [0:13:5])
print("rajashreemoon" [::4])
print(lang[1::2])
print("pooja" [4::-1])
print("rajashreemoon" [12::-2])