number=2 #(variable (number) and we can change the value of variable)
print (number)
number=4
print (number)
name="pooja" #(double quote or single quote is mandatory bcz pooja is string)
print (name)
name=123  #(hence python is dynamic programming language)
print (name)
_name="pooja" #(variable start with any letter or _)
print (_name)
user_one_name="amita" #(snake case writing used in python)
print(user_one_name)
userOneName="rajui" #(camel case writing)
print(userOneName)